{
    'name': 'HR Job Extension',
    'version': '1.0',
    'category': 'Human Resources',
    'summary': 'Mở rộng chức năng Chức vụ của module Bộ Máy Tổ Chức',
    'description': """Mô-đun mở rộng để quản lý thông tin Chức vụ, bao gồm phụ cấp và thông tin tuyển dụng.""",
    'author': 'Generated by ChatGPT',
    'depends': ['hr'],
    # DÙNG "assets" để load JS/CSS vào web client
    'assets': {
        'web.assets_backend': [
            # Tiptap core + StarterKit
            'bo_may_to_chuc_hr_job_slash/static/lib/tiptap/tiptap.umd.js',
            # Slash menu plugin bạn tự viết
            'bo_may_to_chuc_hr_job_slash/static/lib/tiptap/slash-menu.umd.js',
            # Widget JS khởi tạo editor
            'bo_may_to_chuc_hr_job_slash/static/src/js/slash_text_widget.js',
            # XML template để include script (nếu bạn dùng slash_text_assets.xml)
            'bo_may_to_chuc_hr_job_slash/static/src/xml/slash_text_assets.xml',
        ],
    },
    'data': [
        'security/ir.model.access.csv',
        'views/hr_job_custom_views.xml',
    ],
    'installable': True,
    'application': False,
}
