from . import hr_job_custom
from . import res_company_custom
from . import res_company_insurance_line
from . import res_company_location_line
from . import res_country_district
from . import res_country_street
from . import hr_employee_custom
from . import hr_department_custom
from . import hr_position_assignment
from . import x_contract_appendix
from . import x_contract_appendix_allowance
from . import hr_contract_custom